name: junto_beta_mobile
description: A new Flutter project.

version: 1.0.1+14

environment:
  sdk: ">=2.6.0-dev <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: 0.6.3+4
  shared_preferences: 0.5.6+2
  cupertino_icons: 0.1.3
  provider: 4.0.4
  http: 0.12.0+4
  sentry: 3.0.0+1
  localstorage: 3.0.1+4
  giphy_client: 0.2.0
  cached_network_image:
    git: https://github.com/juntofoundation/flutter_cached_network_image
  carousel_slider: 1.4.1
  flutter_spinkit: 4.1.2
  path_provider: 1.6.1
  flutter_slidable: 0.5.4
  package_info: 0.4.0+14
  keyboard_avoider: 0.1.2
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  equatable: ^1.1.1
  json_serializable: ^3.2.5
  freezed_annotation: ^0.7.1
  dio: ^3.0.9
  animations: ^1.0.0+5
  url_launcher: 5.4.2

dependency_overrides:
  path_provider: 1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner:
  freezed:
  effective_dart:

flutter:
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 700

    - family: j_home
      fonts:
        - asset: assets/fonts/j_home.ttf

    - family: j_home_two
      fonts:
        - asset: assets/fonts/j_home_two.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/emoji.json
    - assets/images/junto-mobile__themes--rainbow.png
    - assets/images/junto-mobile__themes--aqueous.png
    - assets/images/junto-mobile__themes--royal.png
    - assets/images/junto-mobile__themes--night.png
    - assets/images/junto-mobile__logo.png
    - assets/images/junto-mobile__outlinelogo--gradient.png
    - assets/images/junto-mobile__infinity.png
    - assets/images/junto-mobile__location.png
    - assets/images/junto-mobile__link.png
    - assets/images/junto-mobile__binoculars.png
    - assets/images/junto-mobile__double-up-arrow.png
    - assets/images/junto-mobile__double-down-arrow.png
    - assets/images/junto-mobile__menu.png
    - assets/images/junto-mobile__filter.png
