name: junto_beta_mobile
description: A new Flutter project.

version: 1.0.2+1

environment:
  sdk: ">=2.6.0-dev <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: 0.6.6+1
  shared_preferences: 0.5.7
  cupertino_icons: 0.1.3
  provider: 4.0.5+1
  http: 0.12.1
  sentry: 3.0.0+1
  localstorage: 3.0.1+4
  giphy_client: 0.2.0
  flutter_cache_manager: 1.2.2
  cached_network_image: 2.2.0+1
  flutter_spinkit: 4.1.2
  path_provider: 1.6.8
  flutter_slidable: 0.5.4
  package_info: 0.4.0+14
  keyboard_avoider: 0.1.2
  flutter_bloc: 4.0.0
  rxdart: 0.24.0
  equatable: 1.1.1
  json_serializable: 3.2.5
  freezed_annotation: 0.7.1
  dio: 3.0.9
  animations: 1.0.0+5
  url_launcher: 5.4.5
  stack_trace: 1.9.3
  feature_discovery: 0.8.0
  device_preview: 0.4.1+1
  intl: ^0.16.1
  audioplayers: 0.15.1
  flutter_native_image: 0.0.5
  flutter_audio_recorder: 0.5.5
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  data_connection_checker: 0.3.4
  vibration: 1.2.4  
  custom_refresh_indicator: ^0.8.0+1
  flutter_staggered_grid_view: 0.3.0
  
dev_dependencies:
  test: any
  build_runner: 1.9.0
  hive_generator: 0.7.0+2
  freezed: 0.10.7
  effective_dart: 1.2.1
dependency_overrides:
  path: 1.7.0
flutter:
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 700

    - family: j_home
      fonts:
        - asset: assets/fonts/j_home.ttf

    - family: j_home_two
      fonts:
        - asset: assets/fonts/j_home_two.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/emoji.json
    - assets/images/junto-mobile__themes--rainbow.png
    - assets/images/junto-mobile__themes--aqueous.png
    - assets/images/junto-mobile__themes--royal.png
    - assets/images/junto-mobile__themes--night.png
    - assets/images/junto-mobile__logo.png
    - assets/images/junto-mobile__outlinelogo--gradient.png
    - assets/images/junto-mobile__infinity.png
    - assets/images/junto-mobile__location.png
    - assets/images/junto-mobile__link.png
    - assets/images/junto-mobile__binoculars.png
    - assets/images/junto-mobile__double-up-arrow.png
    - assets/images/junto-mobile__double-down-arrow.png
    - assets/images/junto-mobile__menu.png
    - assets/images/junto-mobile__filter.png
    - assets/images/junto-mobile__groups--placeholder.png
    - assets/images/junto-mobile__placeholder--notifications.png
    - assets/images/junto-mobile__waveform.png

flutter_intl:
  enabled: true
  main_locale: en
  localizely:
    project_id: 8a7cdfd2-aaef-4e44-a773-9c9801bf1c69
