name: junto_beta_mobile
description: A new Flutter project.

version: 1.0.2+1

environment:
  sdk: ">=2.6.0-dev <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: 0.6.7+3
  shared_preferences: 0.5.7
  cupertino_icons: 0.1.3
  provider: ^4.1.3
  http: 0.12.1
  sentry: 3.0.0+1
  giphy_client: 0.2.0
  flutter_cache_manager: 1.4.1
  cached_network_image: 2.2.0+1
  flutter_spinkit: 4.1.2
  path_provider: 1.6.8
  package_info: 0.4.1
  keyboard_avoider: 0.1.2
  flutter_bloc: ^6.0.0
  rxdart: 0.24.1
  equatable: ^1.2.0
  json_serializable: 3.3.0
  freezed_annotation: 0.11.0
  dio: 3.0.9
  url_launcher: 5.4.11
  feature_discovery: 0.8.0
  intl: ^0.16.1
  audioplayers: 0.15.1
  flutter_audio_recorder: 0.5.5
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  data_connection_checker: 0.3.4
  vibration: 1.4.0
  custom_refresh_indicator: ^0.8.0+1
  flutter_staggered_grid_view: 0.3.0
  image: 2.1.13
  expandable: any
  flutter_aws_amplify_cognito: 1.0.0+7
  corsac_jwt: ^0.2.2
  flutter_linkify: 3.1.3

dev_dependencies:
  test: any
  build_runner: 1.10.0
  hive_generator: 0.7.0+2
  freezed: 0.11.2
  effective_dart: 1.2.3
  preview: 0.0.8
dependency_overrides:
  dartx: 0.5.0
  characters: 1.0.0
  path: 1.7.0
  # Overriding due to crash on iOS https://github.com/agnostech/flutter_amplify/pull/12
  flutter_aws_amplify_cognito:
    # path: ../flutter_amplify/flutter_aws_amplify_cognito
    git:
      url: https://github.com/orestesgaolin/flutter_amplify.git
      path: flutter_aws_amplify_cognito
      ref: 9e835abe5a8602b16a7b8ea6d8f3ed3a1f21f5b6

flutter:
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 700

    - family: j_home
      fonts:
        - asset: assets/fonts/j_home.ttf

    - family: j_home_two
      fonts:
        - asset: assets/fonts/j_home_two.ttf

    - family: j_home_three
      fonts:
        - asset: assets/fonts/j_home_three.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/emoji.json
    - assets/images/junto-mobile__themes--rainbow.png
    - assets/images/junto-mobile__themes--aqueous.png
    - assets/images/junto-mobile__themes--royal.png
    - assets/images/junto-mobile__themes--fire.png
    - assets/images/junto-mobile__themes--forest.png
    - assets/images/junto-mobile__themes--dark.png
    - assets/images/junto-mobile__themes--sand.png
    - assets/images/junto-mobile__logo.png
    - assets/images/junto-mobile__logo--white.png
    - assets/images/junto-mobile__logo--rainbow.png
    - assets/images/junto-mobile__logo--aqueous.png
    - assets/images/junto-mobile__logo--purpgold.png
    - assets/images/junto-mobile__logo--sand.png
    - assets/images/junto-mobile__logo--dark.png
    - assets/images/junto-mobile__logo--fire.png
    - assets/images/junto-mobile__logo--forest.png
    - assets/images/junto-mobile__logo-outline--white.png
    - assets/images/junto-mobile__logo-outline--rainbow.png
    - assets/images/junto-mobile__logo-outline--aqueous.png
    - assets/images/junto-mobile__logo-outline--purpgold.png
    - assets/images/junto-mobile__logo-outline--sand.png
    - assets/images/junto-mobile__logo-outline--dark.png
    - assets/images/junto-mobile__logo-outline--fire.png
    - assets/images/junto-mobile__logo-outline--forest.png    
    - assets/images/junto-mobile__outlinelogo--gradient.png
    - assets/images/junto-mobile__infinity.png
    - assets/images/junto-mobile__location.png
    - assets/images/junto-mobile__link.png
    - assets/images/junto-mobile__binoculars.png
    - assets/images/junto-mobile__double-up-arrow.png
    - assets/images/junto-mobile__double-down-arrow.png
    - assets/images/junto-mobile__menu.png
    - assets/images/junto-mobile__line.png
    - assets/images/junto-mobile__filter.png
    - assets/images/junto-mobile__groups--placeholder.png
    - assets/images/junto-mobile__placeholder--notifications.png
    - assets/images/junto-mobile__placeholder--feed.png
    - assets/images/junto-mobile__waveform.png
    - assets/images/junto-mobile__perspective--white.png
    - assets/images/junto-mobile__perspective--rainbow.png
    - assets/images/junto-mobile__perspective--aqueous.png
    - assets/images/junto-mobile__perspective--purpgold.png
    - assets/images/junto-mobile__perspective--sand.png
    - assets/images/junto-mobile__perspective--fire.png
    - assets/images/junto-mobile__perspective--forest.png
    - assets/images/junto-mobile__perspective--dark.png
    - assets/images/junto-mobile__sprout.png
    - assets/images/junto-mobile__background.png

flutter_intl:
  enabled: true
  main_locale: en
  localizely:
    project_id: 8a7cdfd2-aaef-4e44-a773-9c9801bf1c69
